server:
  port: 8081

spring:
  application:
    name: temperature-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smarthome}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: WARN
    org.hibernate:
      SQL: INFO
      type.descriptor.sql.BasicBinder: TRACE
