server:
  port: 8082

spring:
  application:
    name: sensor-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-sensor:5432/smarthome}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

legacy:
  temperature-api:
    url: ${LEGACY_TEMPERATURE_API_URL:http://localhost:8081}
    timeout: 10s

logging:
  level:
    root: WARN
    org.springframework.kafka: INFO
